window.grantsData = [
  {
    "program_name": "Google Play Indie Games Fund",
    "provider": "Google Play",
    "country": "Latin America",
    "sector_focus": "App Dev, Gaming",
    "funding_type": "Grant + Support",
    "funding_amount": "$2,000,000 Fund",
    "eligibility_summary": "Indie game studios and app developers.",
    "deadline": "2026-08-15",
    "application_link": "https://developer.android.com/distribute/google-play/indie-games-fund",
    "source_category": "Corporate",
    "effort_level": "High",
    "awards_available": "10 Studios",
    "open_date": "2026-06-01",
    "id": "a6df167a3df40876c7ce4b01257010b6",
    "relevance_score": 85,
    "priority": "MEDIUM",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-26",
    "last_updated": "2026-02-26"
  },
  {
    "program_name": "Apple Entrepreneur Camp",
    "provider": "Apple",
    "country": "Global",
    "sector_focus": "App Dev, iOS",
    "funding_type": "Mentorship + Hardware",
    "funding_amount": "Unknown",
    "eligibility_summary": "Underrepresented founders building apps.",
    "deadline": "2026-09-01",
    "application_link": "https://developer.apple.com/entrepreneur-camp/",
    "source_category": "Corporate",
    "effort_level": "Medium",
    "awards_available": "Varies",
    "open_date": "Rolling",
    "id": "4234244b73bbcab1f52498cd04b58183",
    "relevance_score": 72,
    "priority": "LOW",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-26",
    "last_updated": "2026-02-26"
  },
  {
    "program_name": "a16z GAMES SPEEDRUN",
    "provider": "Andreessen Horowitz",
    "country": "Global",
    "sector_focus": "Gaming, Web3",
    "funding_type": "Equity ($500k)",
    "funding_amount": "$500,000",
    "eligibility_summary": "High potential gaming startups.",
    "deadline": "2026-05-01",
    "application_link": "https://a16z.com/speedrun/",
    "source_category": "VC",
    "effort_level": "High",
    "awards_available": "40 Teams",
    "open_date": "2026-03-01",
    "id": "866a8a8df0222e2c31cabc5121031f48",
    "relevance_score": 76,
    "priority": "MEDIUM",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-26",
    "last_updated": "2026-02-26"
  },
  {
    "program_name": "Google for Startups: AI Fund",
    "provider": "Google",
    "country": "Europe / Israel",
    "sector_focus": "AI, Cloud, Data",
    "funding_type": "Equity-Free Support",
    "funding_amount": "$350,000 (Cloud Credits)",
    "eligibility_summary": "AI-first startups.",
    "deadline": "2026-04-01",
    "application_link": "https://campus.co/",
    "source_category": "Private",
    "effort_level": "Low",
    "awards_available": "20 Startups",
    "open_date": "2026-01-20",
    "id": "881610a89bbd320bca8b878fbf604be5",
    "relevance_score": 79,
    "priority": "MEDIUM",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-26",
    "last_updated": "2026-02-26"
  },
  {
    "program_name": "Reach Capital EdTech Fellowship",
    "provider": "Reach Capital",
    "country": "USA / Global",
    "sector_focus": "EdTech, Learning",
    "funding_type": "Equity",
    "funding_amount": "$150,000",
    "eligibility_summary": "Founders building the future of learning.",
    "deadline": "2026-05-20",
    "application_link": "https://reachcapital.com",
    "source_category": "VC",
    "effort_level": "High",
    "awards_available": "10 Teams",
    "open_date": "2026-02-01",
    "id": "a4b7eee59e2f0bb1e6fb9db9642edcc7",
    "relevance_score": 76,
    "priority": "MEDIUM",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-26",
    "last_updated": "2026-02-26"
  },
  {
    "program_name": "Epic Games MegaGrants",
    "provider": "Epic Games",
    "country": "Global",
    "sector_focus": "Gaming, 3D, Creative",
    "funding_type": "Grant",
    "funding_amount": "$5,000 - $500,000",
    "eligibility_summary": "Creators using Unreal Engine or open source 3D content.",
    "deadline": "Rolling",
    "application_link": "https://www.unrealengine.com/en-US/megagrants",
    "source_category": "Private",
    "effort_level": "Medium",
    "awards_available": "Rolling Basis",
    "open_date": "Rolling",
    "id": "9b46634e475850cdcb2fd7c481710aa5",
    "relevance_score": 86,
    "priority": "MEDIUM",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-26",
    "last_updated": "2026-02-26"
  },
  {
    "program_name": "Thiel Fellowship",
    "provider": "Thiel Foundation",
    "country": "Global",
    "sector_focus": "Builders",
    "funding_type": "Grant",
    "funding_amount": "$100,000",
    "eligibility_summary": "Under 23, drop out of school.",
    "deadline": "Rolling",
    "application_link": "https://thielfellowship.org/",
    "source_category": "Private",
    "effort_level": "Medium",
    "awards_available": "20 Fellows",
    "open_date": "Rolling",
    "id": "67d2c5570a062e419e6829d2fc459691",
    "relevance_score": 86,
    "priority": "MEDIUM",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-26",
    "last_updated": "2026-02-26"
  },
  {
    "program_name": "UNICEF Innovation Fund",
    "provider": "UNICEF",
    "country": "Global (Emerging Markets)",
    "sector_focus": "Social Impact, Open Source",
    "funding_type": "Grant",
    "funding_amount": "$100,000 (0% Equity)",
    "eligibility_summary": "Open source technology for children.",
    "deadline": "2026-08-01",
    "application_link": "https://www.unicefinnovationfund.org/",
    "source_category": "Non-Profit",
    "effort_level": "High",
    "awards_available": "Varies",
    "open_date": "2026-06-01",
    "id": "9ab5d546de5e787bbf485980a2ffe676",
    "relevance_score": 85,
    "priority": "MEDIUM",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-26",
    "last_updated": "2026-02-26"
  },
  {
    "program_name": "Y Combinator S26",
    "provider": "Y Combinator",
    "country": "Global (Remote Friendly)",
    "sector_focus": "Tech, B2B, Consumer",
    "funding_type": "Equity ($125k for 7%)",
    "funding_amount": "$500,000",
    "eligibility_summary": "Early stage startups.",
    "deadline": "2026-04-15",
    "application_link": "https://www.ycombinator.com/apply",
    "source_category": "Accelerator",
    "effort_level": "Medium",
    "awards_available": "250 Cohort Seats",
    "open_date": "2026-01-15",
    "id": "e7aacac56ed09f857c6ed61a0f239799",
    "relevance_score": 80,
    "priority": "MEDIUM",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-26",
    "last_updated": "2026-02-26"
  },
  {
    "program_name": "NSF SBIR Phase I",
    "provider": "National Science Foundation",
    "country": "USA",
    "sector_focus": "DeepTech, R&D",
    "funding_type": "Grant (Non-dilutive)",
    "funding_amount": "$275,000",
    "eligibility_summary": "US-based small businesses engaging in R&D.",
    "deadline": "2026-07-05",
    "application_link": "https://seedfund.nsf.gov/",
    "source_category": "Gov",
    "effort_level": "High",
    "awards_available": "300+ Awards",
    "open_date": "2026-03-15",
    "id": "65107879b60ee61ea36081fae91b2940",
    "relevance_score": 90,
    "priority": "HIGH",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-26",
    "last_updated": "2026-02-26"
  },
  {
    "program_name": "Fast Track High Score Grant",
    "provider": "Test Provider",
    "country": "Global",
    "sector_focus": "General",
    "funding_type": "Grant",
    "funding_amount": "$100,000",
    "eligibility_summary": "Open to all.",
    "deadline": "2026-03-01",
    "application_link": "https://example.com",
    "source_category": "Gov",
    "effort_level": "Low",
    "id": "c60f21ae534274b9e59585286ed8bb12",
    "relevance_score": 95,
    "priority": "HIGH",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-17",
    "last_updated": "2026-02-17"
  },
  {
    "program_name": "OpenAI Residency",
    "provider": "OpenAI",
    "country": "US (Remote Friendly)",
    "sector_focus": "AI, ML Research",
    "funding_type": "Salary + Equity",
    "funding_amount": "$210,000 / year",
    "eligibility_summary": "Exceptional researchers.",
    "deadline": "2026-06-01",
    "application_link": "https://openai.com/careers",
    "source_category": "Private",
    "effort_level": "High",
    "id": "64149b106b0938cafb01aaaf477884d4",
    "relevance_score": 81,
    "priority": "MEDIUM",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-17",
    "last_updated": "2026-02-17"
  },
  {
    "program_name": "Horizon Europe EIC Accelerator",
    "provider": "European Commission",
    "country": "Europe",
    "sector_focus": "DeepTech, GreenTech, Health",
    "funding_type": "Grant + Equity",
    "funding_amount": "Up to \u20ac2.5M Grant + \u20ac15M Equity",
    "eligibility_summary": "SMEs with radical innovation.",
    "deadline": "2026-06-05",
    "application_link": "https://eic.ec.europa.eu",
    "source_category": "Gov",
    "effort_level": "Extreme",
    "id": "67c852af3b405e90cbe6ae9f0f574937",
    "relevance_score": 90,
    "priority": "HIGH",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-17",
    "last_updated": "2026-02-17"
  },
  {
    "program_name": "Google for Startups Cloud Program",
    "provider": "Google Cloud",
    "country": "Global",
    "sector_focus": "AI, Web3, SaaS",
    "funding_type": "Credits (Non-dilutive)",
    "funding_amount": "Up to $350,000 (Credits)",
    "eligibility_summary": "Series A or lower. Verified domain.",
    "deadline": "Open All Year",
    "application_link": "https://cloud.google.com/startup",
    "source_category": "Private",
    "effort_level": "Low",
    "id": "b0d4670477b663ff4d0e431fa6cc121e",
    "relevance_score": 82,
    "priority": "MEDIUM",
    "status": "Not Applied",
    "notes": "",
    "added_date": "2026-02-17",
    "last_updated": "2026-02-17"
  },
  {
    "program_name": "Y Combinator W26 Batch",
    "provider": "Y Combinator",
    "country": "Global (US based)",
    "sector_focus": "Sector Agnostic",
    "funding_type": "Equity Investment",
    "funding_amount": "$500,000",
    "eligibility_summary": "Early stage. High growth potential.",
    "deadline": "2026-04-15",
    "application_link": "https://www.ycombinator.com/apply",
    "required_documents": [
      "Founder Video",
      "Demo"
    ],
    "effort_level": "High",
    "relevance_score": 80,
    "priority": "MEDIUM",
    "id": "7694cc7872f2f8cb44c16ea7def69320",
    "source_category": "Accelerator",
    "last_updated": "2026-02-17"
  },
  {
    "program_name": "ELEVATE NXT 2026",
    "provider": "Government of Karnataka (Startup Karnataka)",
    "country": "India",
    "sector_focus": "DeepTech, AI, Data, Health, Energy, Manufacturing",
    "funding_type": "Grant-in-aid (Non-dilutive)",
    "funding_amount": "Up to \u20b91 Crore",
    "eligibility_summary": "DPIIT/Karnataka recognized startups. Innovation in DeepTech. MVP/PoC stage.",
    "deadline": "2026-02-17",
    "application_link": "https://missionstartupkarnataka.org",
    "required_documents": [
      "Pitch Deck",
      "Incorporation Cert",
      "DPIIT/Karnataka Recognition",
      "PoC Validation Details"
    ],
    "effort_level": "High",
    "relevance_score": 95,
    "priority": "High",
    "id": "81d4e2723ee4c92ec61c04056fe84650"
  },
  {
    "program_name": "HDFC Parivartan Start-up Grants 2026",
    "provider": "HDFC Bank",
    "country": "India",
    "sector_focus": "Social Impact, AI, DeepTech, Climate, Agriculture, Financial Inclusion",
    "funding_type": "Grant (Non-dilutive)",
    "funding_amount": "Varies (Total corpus \u20b920 Cr)",
    "eligibility_summary": "Social impact focus. Innovation in priority sectors. Incubator-partnered application.",
    "deadline": "2026-02-15",
    "application_link": "Via Partner Incubators (e.g., IITM, IIMB NSRCEL)",
    "required_documents": [
      "Proposal",
      "Budget Plan",
      "Incubator Endorsement"
    ],
    "effort_level": "High",
    "relevance_score": 90,
    "priority": "High",
    "id": "586f4b966adb336c09acb8730a20cb78"
  },
  {
    "program_name": "Startup India Seed Fund Scheme (SISFS)",
    "provider": "DPIIT / Government of India",
    "country": "India",
    "sector_focus": "Sector Agnostic (Tech preferred)",
    "funding_type": "Grant (up to \u20b920L) & Debt/Convertible (up to \u20b950L)",
    "funding_amount": "INR 20 Lakhs (Grant) + INR 50 Lakhs (Investment)",
    "eligibility_summary": "DPIIT Recognized, <2 years old, Business idea to commercialization stage.",
    "deadline": "Open All Year",
    "application_link": "https://seedfund.startupindia.gov.in",
    "required_documents": [
      "DPIIT Recognition",
      "Pitch Deck",
      "Video Pitch",
      "Cap Table"
    ],
    "effort_level": "Medium",
    "relevance_score": 85,
    "priority": "High",
    "id": "201cc53a99737c0b6245445bb18a2701"
  },
  {
    "program_name": "Microsoft for Startups Founders Hub",
    "provider": "Microsoft",
    "country": "Global (Active in India)",
    "sector_focus": "Technology, AI, SaaS",
    "funding_type": "Credits & Resources (Non-dilutive)",
    "funding_amount": "$1,000 - $150,000 (Credits)",
    "eligibility_summary": "Tech-based startups. Pre-Series B. No funding required for entry tier.",
    "deadline": "Open All Year",
    "application_link": "https://foundershub.startups.microsoft.com",
    "required_documents": [
      "LinkedIn Profile",
      "Company Website",
      "Pitch Deck (optional for low tier)"
    ],
    "effort_level": "Low",
    "relevance_score": 80,
    "priority": "Medium",
    "id": "8220761cfd77e442346b085d43c93ae7"
  },
  {
    "program_name": "AWS Activate",
    "provider": "Amazon Web Services",
    "country": "Global (Active in India)",
    "sector_focus": "Technology",
    "funding_type": "Credits (Non-dilutive)",
    "funding_amount": "$1,000 - $100,000 (Credits)",
    "eligibility_summary": "Bootstrapped (Founders tier) or Provider-affiliated (Portfolio tier). <10 years old.",
    "deadline": "Open All Year",
    "application_link": "https://aws.amazon.com/activate",
    "required_documents": [
      "Company Website",
      "AWS Account ID",
      "Org ID (for Portfolio)"
    ],
    "effort_level": "Low",
    "relevance_score": 75,
    "priority": "Medium",
    "id": "3a4227e5d61fbdb304af25240f372906"
  }
];